import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv

load_dotenv()

def send_summary_email(mentor_email, student_name, date_str, summary_text):
    sender_email = os.environ.get("SMTP_EMAIL")
    sender_password = os.environ.get("SMTP_PASSWORD")
    
    if not sender_email or not sender_password:
        raise ValueError("SMTP credentials are not configured in environment variables. Please set SMTP_EMAIL and SMTP_PASSWORD.")
        
    if not mentor_email:
        raise ValueError("Mentor email is not configured for this student.")
        
    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = mentor_email
    msg['Subject'] = f"Mentis.ai Daily Summary: {student_name} ({date_str})"
    
    body = f"Hello,\n\nHere is the automated daily summary for {student_name} on {date_str}:\n\n"
    body += "-" * 50 + "\n"
    body += summary_text + "\n"
    body += "-" * 50 + "\n\n"
    body += "Generated by Mentis.ai."
    
    msg.attach(MIMEText(body, 'plain'))
    
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        text = msg.as_string()
        server.sendmail(sender_email, mentor_email, text)
        server.quit()
        return True
    except Exception as e:
        raise Exception(f"Failed to send email: {e}")
